# Generated by Django 6.0.1 on 2026-01-30 13:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('health_check_interval', models.PositiveIntegerField(default=60, help_text='Interval in minutes between health checks', validators=[django.core.validators.MinValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='systems.system')),
            ],
            options={
                'indexes': [models.Index(fields=['system'], name='systems_ser_system__ff94f7_idx'), models.Index(fields=['is_active'], name='systems_ser_is_acti_fa772f_idx')],
            },
        ),
    ]
