# Generated by Django 6.0.1 on 2026-02-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='prefix_token',
            field=models.CharField(default='bot_token_', max_length=12),
        ),
    ]
